### ISSUE TITLE
Widget gets stuck in the "hot" state

### ISSUE THREAD

**Issue by jeratt** [vrld/SUIT#10]
Usually the first widget. This even happens in the example code in the readme.
![screen shot 2013-07-01 at 4 55 10 pm](https://f.cloud.github.com/assets/246279/732939/900f91cc-e290-11e2-9be9-c9e4557193dc.png)

**Comment by Billiam** [comment]
Old ticket, but what is the best way of altering this behavior without making changes to library code? 

The tryGrab method is exposed in the keyboard module, but all references to that and other methods take place via closures, making them quite private. (ex: gui.keyboard.tryGrab could be replaced, but is referenced by closure in gui.keyboard.makeCyclable. makeCyclable would also need to be replaced).

Similarly, while gui.keyboard coulde be replaced with some other module (like one which delegated to the original keyboard module), keyboard is required in directly from button, checkbox, core, etc rather than pulled from a central object, and so cannot be replaced or decorated.

**Comment by vrld** [comment]
You can disable keyboard focus with `gui.keyboard.disable()`. However, that completely disables keyboard input, even in places where it might be wanted.

I originally did not intent the library functions to be replacable, but I see why this might be useful.

**Comment by vrld** [comment]
Closed, because SUIT does not do keyboard cycling anymore.
